"""baseline 2025-10-30

Revision ID: 0001
Revises: 
Create Date: 2025-10-30 17:01:09.258758

"""

import json

import sqlalchemy as sa
from alembic import op
from alembic_utils.pg_function import PGFunction
from alembic_utils.pg_trigger import PGTrigger
from slugify import slugify
from sqlalchemy.dialects import postgresql
from sqlalchemy.ext.automap import automap_base
from sqlalchemy.orm import Session
from sqlalchemy.sql import text

from db_client.models.dfce.geography import CPR_DEFINED_GEOS, GEO_OTHER
from db_client.utils import get_library_path

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None

Base = automap_base()


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "app_user",
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("hashed_password", sa.String(), nullable=True),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("email", name=op.f("pk_app_user")),
    )

    op.create_table(
        "collection",
        sa.Column("import_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "valid_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("import_id", name=op.f("pk_collection")),
    )

    op.create_table(
        "corpus_type",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "valid_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_corpus_type")),
    )

    op.create_table(
        "family",
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("import_id", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column(
            "family_category",
            sa.Enum(
                "EXECUTIVE",
                "LEGISLATIVE",
                "UNFCCC",
                "MCF",
                "REPORTS",
                "LITIGATION",
                name="familycategory",
            ),
            nullable=False,
        ),
        sa.Column(
            "concepts",
            postgresql.ARRAY(postgresql.JSONB(astext_type=sa.Text())),
            nullable=True,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("import_id", name=op.f("pk_family")),
    )
    op.create_index(op.f("ix_family_import_id"), "family", ["import_id"], unique=True)

    op.create_table(
        "geography",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("display_value", sa.Text(), nullable=False),
        sa.Column("slug", sa.Text(), nullable=False),
        sa.Column("value", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["geography.id"],
            name=op.f("fk_geography__parent_id__geography"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geography")),
    )
    op.create_index(op.f("ix_geography_slug"), "geography", ["slug"], unique=True)

    op.create_table(
        "language",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("language_code", sa.CHAR(length=3), nullable=False),
        sa.Column("part1_code", sa.CHAR(length=2), nullable=True),
        sa.Column("part2_code", sa.CHAR(length=3), nullable=True),
        sa.Column("name", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_language")),
        sa.UniqueConstraint("language_code", name=op.f("uq_language__language_code")),
    )

    op.create_table(
        "organisation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("organisation_type", sa.String(), nullable=True),
        sa.Column("attribution_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organisation")),
        sa.UniqueConstraint("name", name=op.f("uq_organisation__name")),
    )

    op.create_table(
        "physical_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("md5_sum", sa.Text(), nullable=True),
        sa.Column("cdn_object", sa.Text(), nullable=True),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("content_type", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_physical_document")),
    )

    op.create_table(
        "variant",
        sa.Column("variant_name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("variant_name", name=op.f("pk_variant")),
    )

    op.create_table(
        "collection_family",
        sa.Column("collection_import_id", sa.Text(), nullable=False),
        sa.Column("family_import_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_import_id"],
            ["collection.import_id"],
            name=op.f("fk_collection_family__collection_import_id__collection"),
        ),
        sa.ForeignKeyConstraint(
            ["family_import_id"],
            ["family.import_id"],
            name=op.f("fk_collection_family__family_import_id__family"),
        ),
        sa.PrimaryKeyConstraint(
            "collection_import_id",
            "family_import_id",
            name=op.f("pk_collection_family"),
        ),
    )
    op.create_index(
        op.f("ix_collection_family_family_import_id"),
        "collection_family",
        ["family_import_id"],
        unique=False,
    )

    op.create_table(
        "collection_organisation",
        sa.Column("collection_import_id", sa.Text(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_import_id"],
            ["collection.import_id"],
            name=op.f("fk_collection_organisation__collection_import_id__collection"),
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
            name=op.f("fk_collection_organisation__organisation_id__organisation"),
        ),
        sa.PrimaryKeyConstraint(
            "collection_import_id", name=op.f("pk_collection_organisation")
        ),
    )

    op.create_table(
        "corpus",
        sa.Column("import_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("corpus_text", sa.Text(), nullable=False),
        sa.Column("corpus_image_url", sa.Text(), nullable=True),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("corpus_type_name", sa.Text(), nullable=False),
        sa.Column("attribution_url", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["corpus_type_name"],
            ["corpus_type.name"],
            name=op.f("fk_corpus__corpus_type_name__corpus_type"),
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
            name=op.f("fk_corpus__organisation_id__organisation"),
        ),
        sa.PrimaryKeyConstraint("import_id", name=op.f("pk_corpus")),
    )
    op.create_index(op.f("ix_corpus_import_id"), "corpus", ["import_id"], unique=True)

    op.create_table(
        "entity_counter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("prefix", sa.String(), nullable=False),
        sa.Column("counter", sa.Integer(), server_default="0", nullable=False),
        sa.ForeignKeyConstraint(
            ["prefix"],
            ["organisation.name"],
            name=op.f("fk_entity_counter__prefix__organisation"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_entity_counter")),
    )

    op.create_table(
        "family_document",
        sa.Column("family_import_id", sa.Text(), nullable=False),
        sa.Column("physical_document_id", sa.Integer(), nullable=False),
        sa.Column("import_id", sa.Text(), nullable=False),
        sa.Column("variant_name", sa.Text(), nullable=True),
        sa.Column(
            "document_status",
            sa.Enum("CREATED", "PUBLISHED", "DELETED", name="documentstatus"),
            nullable=False,
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "valid_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["family_import_id"],
            ["family.import_id"],
            name=op.f("fk_family_document__family_import_id__family"),
        ),
        sa.ForeignKeyConstraint(
            ["physical_document_id"],
            ["physical_document.id"],
            name=op.f("fk_family_document__physical_document_id__physical_document"),
        ),
        sa.ForeignKeyConstraint(
            ["variant_name"],
            ["variant.variant_name"],
            name=op.f("fk_family_document__variant_name__variant"),
        ),
        sa.PrimaryKeyConstraint("import_id", name=op.f("pk_family_document")),
        sa.UniqueConstraint(
            "physical_document_id",
            name=op.f("uq_family_document__physical_document_id"),
        ),
    )
    op.create_index(
        op.f("ix_family_document_family_import_id"),
        "family_document",
        ["family_import_id"],
        unique=False,
    )

    op.create_table(
        "family_geography",
        sa.Column("geography_id", sa.Integer(), nullable=False),
        sa.Column("family_import_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_import_id"],
            ["family.import_id"],
            name=op.f("fk_family_geography__family_import_id__family"),
        ),
        sa.ForeignKeyConstraint(
            ["geography_id"],
            ["geography.id"],
            name=op.f("fk_family_geography__geography_id__geography"),
        ),
        sa.PrimaryKeyConstraint(
            "geography_id", "family_import_id", name=op.f("pk_family_geography")
        ),
    )
    op.create_index(
        op.f("ix_family_geography_family_import_id"),
        "family_geography",
        ["family_import_id"],
        unique=False,
    )

    op.create_table(
        "family_metadata",
        sa.Column("family_import_id", sa.Text(), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_import_id"],
            ["family.import_id"],
            name=op.f("fk_family_metadata__family_import_id__family"),
        ),
        sa.PrimaryKeyConstraint("family_import_id", name=op.f("pk_family_metadata")),
    )

    op.create_table(
        "geo_statistics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("geography_id", sa.Integer(), nullable=False),
        sa.Column("legislative_process", sa.Text(), nullable=False),
        sa.Column("federal", sa.Boolean(), nullable=False),
        sa.Column("federal_details", sa.Text(), nullable=False),
        sa.Column("political_groups", sa.Text(), nullable=False),
        sa.Column("global_emissions_percent", sa.Text(), nullable=True),
        sa.Column("climate_risk_index", sa.Text(), nullable=True),
        sa.Column("worldbank_income_group", sa.Text(), nullable=False),
        sa.Column("visibility_status", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["geography_id"],
            ["geography.id"],
            name=op.f("fk_geo_statistics__geography_id__geography"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_geo_statistics")),
        sa.UniqueConstraint("name", name=op.f("uq_geo_statistics__name")),
    )

    op.create_table(
        "organisation_admin",
        sa.Column("appuser_email", sa.String(), nullable=False),
        sa.Column("organisation_id", sa.Integer(), nullable=False),
        sa.Column("job_title", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["appuser_email"],
            ["app_user.email"],
            name=op.f("fk_organisation_admin__appuser_email__app_user"),
        ),
        sa.ForeignKeyConstraint(
            ["organisation_id"],
            ["organisation.id"],
            name=op.f("fk_organisation_admin__organisation_id__organisation"),
        ),
        sa.PrimaryKeyConstraint(
            "appuser_email", "organisation_id", name=op.f("pk_organisation_admin")
        ),
    )

    op.create_table(
        "physical_document_language",
        sa.Column("language_id", sa.Integer(), nullable=False),
        sa.Column("document_id", sa.Integer(), nullable=False),
        sa.Column(
            "source", sa.Enum("USER", "MODEL", name="languagesource"), nullable=False
        ),
        sa.Column("visible", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_id"],
            ["physical_document.id"],
            name=op.f("fk_physical_document_language__document_id__physical_document"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["language_id"],
            ["language.id"],
            name=op.f("fk_physical_document_language__language_id__language"),
        ),
        sa.PrimaryKeyConstraint(
            "language_id",
            "document_id",
            "source",
            name=op.f("pk_physical_document_language"),
        ),
    )
    op.create_index(
        op.f("ix_physical_document_language_document_id"),
        "physical_document_language",
        ["document_id"],
        unique=False,
    )

    op.create_table(
        "family_corpus",
        sa.Column("family_import_id", sa.Text(), nullable=False),
        sa.Column("corpus_import_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["corpus_import_id"],
            ["corpus.import_id"],
            name=op.f("fk_family_corpus__corpus_import_id__corpus"),
        ),
        sa.ForeignKeyConstraint(
            ["family_import_id"],
            ["family.import_id"],
            name=op.f("fk_family_corpus__family_import_id__family"),
        ),
        sa.PrimaryKeyConstraint("family_import_id", name=op.f("pk_family_corpus")),
    )
    op.create_index(
        op.f("ix_family_corpus_corpus_import_id"),
        "family_corpus",
        ["corpus_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_family_corpus_family_import_id"),
        "family_corpus",
        ["family_import_id"],
        unique=False,
    )

    op.create_table(
        "family_event",
        sa.Column("import_id", sa.Text(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("event_type_name", sa.Text(), nullable=False),
        sa.Column("family_import_id", sa.Text(), nullable=False),
        sa.Column("family_document_import_id", sa.Text(), nullable=True),
        sa.Column(
            "status", sa.Enum("OK", "DUPLICATED", name="eventstatus"), nullable=False
        ),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_modified",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "valid_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["family_document_import_id"],
            ["family_document.import_id"],
            name=op.f("fk_family_event__family_document_import_id__family_document"),
        ),
        sa.ForeignKeyConstraint(
            ["family_import_id"],
            ["family.import_id"],
            name=op.f("fk_family_event__family_import_id__family"),
        ),
        sa.PrimaryKeyConstraint("import_id", name=op.f("pk_family_event")),
    )
    op.create_index(
        op.f("ix_family_event_family_document_import_id"),
        "family_event",
        ["family_document_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_family_event_family_import_id"),
        "family_event",
        ["family_import_id"],
        unique=False,
    )

    op.create_table(
        "slug",
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("family_import_id", sa.Text(), nullable=True),
        sa.Column("family_document_import_id", sa.Text(), nullable=True),
        sa.Column("collection_import_id", sa.Text(), nullable=True),
        sa.Column(
            "created",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "num_nonnulls(family_import_id, family_document_import_id, collection_import_id) = 1",
            name=op.f("ck_slug__must_reference_exactly_one_entity"),
        ),
        sa.ForeignKeyConstraint(
            ["collection_import_id"],
            ["collection.import_id"],
            name=op.f("fk_slug__collection_import_id__collection"),
        ),
        sa.ForeignKeyConstraint(
            ["family_document_import_id"],
            ["family_document.import_id"],
            name=op.f("fk_slug__family_document_import_id__family_document"),
        ),
        sa.ForeignKeyConstraint(
            ["family_import_id"],
            ["family.import_id"],
            name=op.f("fk_slug__family_import_id__family"),
        ),
        sa.PrimaryKeyConstraint("name", name="pk_slug"),
    )
    op.create_index(
        op.f("ix_slug_collection_import_id"),
        "slug",
        ["collection_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slug_family_document_import_id"),
        "slug",
        ["family_document_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slug_family_import_id"), "slug", ["family_import_id"], unique=False
    )

    # Create audit helper functions
    public_update_1_last_modified = PGFunction(
        schema="public",
        signature="update_1_last_modified()",
        definition="""
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.last_modified = NOW();
        RETURN NEW;
    END;
    $$ language 'plpgsql'""",
    )
    op.create_entity(public_update_1_last_modified)  # type: ignore

    public_update_2_family_last_modified = PGFunction(
        schema="public",
        signature="update_2_family_last_modified()",
        definition="""
    RETURNS TRIGGER AS $$
    BEGIN
        if tg_op = 'DELETE' then
            UPDATE family
            SET last_modified = NOW()
            WHERE import_id = OLD.family_import_id;
        else
            UPDATE family
            SET last_modified = NOW()
            WHERE import_id = NEW.family_import_id;
        end if;
        RETURN NEW;
    END;
    $$ language 'plpgsql'""",
    )
    op.create_entity(public_update_2_family_last_modified)  # type: ignore

    public_update_2_collection_last_modified = PGFunction(
        schema="public",
        signature="update_2_collection_last_modified()",
        definition="""
    RETURNS TRIGGER AS $$
    BEGIN
        if tg_op = 'DELETE' then
            UPDATE collection
            SET last_modified = NOW()
            WHERE import_id = OLD.collection_import_id;
        else
            UPDATE collection
            SET last_modified = NOW()
            WHERE import_id = NEW.collection_import_id;
        end if;
        RETURN NEW;
    END;
    $$ language 'plpgsql'""",
    )
    op.create_entity(public_update_2_collection_last_modified)  # type: ignore

    # Create audit triggers
    public_family_document_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.family_document",
        is_constraint=False,
        definition="""
    BEFORE UPDATE ON public.family_document
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_1_last_modified()""",
    )
    op.create_entity(public_family_document_update_last_modified)  # type: ignore

    public_family_event_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.family_event",
        is_constraint=False,
        definition="""
    BEFORE UPDATE ON public.family_event
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_1_last_modified()""",
    )
    op.create_entity(public_family_event_update_last_modified)  # type: ignore

    public_family_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.family",
        is_constraint=False,
        definition="""
    BEFORE UPDATE ON public.family
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_1_last_modified()""",
    )
    op.create_entity(public_family_update_last_modified)  # type: ignore

    public_family_document_update_family_last_modified = PGTrigger(
        schema="public",
        signature="update_family_last_modified",
        on_entity="public.family_document",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE OR DELETE ON public.family_document
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_2_family_last_modified()""",
    )
    op.create_entity(public_family_document_update_family_last_modified)  # type: ignore

    public_family_event_update_family_last_modified = PGTrigger(
        schema="public",
        signature="update_family_last_modified",
        on_entity="public.family_event",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE OR DELETE ON public.family_event
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_2_family_last_modified()""",
    )
    op.create_entity(public_family_event_update_family_last_modified)  # type: ignore

    public_collection_update_collection_last_modified = PGTrigger(
        schema="public",
        signature="update_collection_last_modified",
        on_entity="public.collection",
        is_constraint=False,
        definition="""
    BEFORE UPDATE ON public.collection
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_1_last_modified()""",
    )
    op.create_entity(public_collection_update_collection_last_modified)  # type: ignore

    public_collection_family_update_collection_last_modified = PGTrigger(
        schema="public",
        signature="update_collection_last_modified",
        on_entity="public.collection_family",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE OR DELETE ON public.collection_family
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_2_collection_last_modified()""",
    )
    op.create_entity(public_collection_family_update_collection_last_modified)  # type: ignore

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    public_collection_family_update_collection_last_modified = PGTrigger(
        schema="public",
        signature="update_collection_last_modified",
        on_entity="public.collection_family",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE OR DELETE ON public.collection_family
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_2_collection_last_modified()""",
    )
    op.drop_entity(public_collection_family_update_collection_last_modified)  # type: ignore

    public_collection_update_collection_last_modified = PGTrigger(
        schema="public",
        signature="update_collection_last_modified",
        on_entity="public.collection",
        is_constraint=False,
        definition="""
    BEFORE UPDATE ON public.collection
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_1_last_modified()""",
    )
    op.drop_entity(public_collection_update_collection_last_modified)  # type: ignore

    public_family_event_update_family_last_modified = PGTrigger(
        schema="public",
        signature="update_family_last_modified",
        on_entity="public.family_event",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE OR DELETE ON public.family_event
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_2_family_last_modified()""",
    )
    op.drop_entity(public_family_event_update_family_last_modified)  # type: ignore

    public_family_document_update_family_last_modified = PGTrigger(
        schema="public",
        signature="update_family_last_modified",
        on_entity="public.family_document",
        is_constraint=False,
        definition="""
    BEFORE INSERT OR UPDATE OR DELETE ON public.family_document
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_2_family_last_modified()""",
    )
    op.drop_entity(public_family_document_update_family_last_modified)  # type: ignore

    public_family_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.family",
        is_constraint=False,
        definition="""
    BEFORE UPDATE ON public.family
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_1_last_modified()""",
    )
    op.drop_entity(public_family_update_last_modified)  # type: ignore

    public_family_event_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.family_event",
        is_constraint=False,
        definition="""
    BEFORE UPDATE ON public.family_event
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_1_last_modified()""",
    )
    op.drop_entity(public_family_event_update_last_modified)  # type: ignore

    public_family_document_update_last_modified = PGTrigger(
        schema="public",
        signature="update_last_modified",
        on_entity="public.family_document",
        is_constraint=False,
        definition="""
    BEFORE UPDATE ON public.family_document
    FOR EACH ROW
    EXECUTE PROCEDURE public.update_1_last_modified()""",
    )
    op.drop_entity(public_family_document_update_last_modified)  # type: ignore

    public_update_2_collection_last_modified = PGFunction(
        schema="public",
        signature="update_2_collection_last_modified()",
        definition="""
    RETURNS TRIGGER AS $$
    BEGIN
        if tg_op = 'DELETE' then
            UPDATE collection
            SET last_modified = NOW()
            WHERE import_id = OLD.collection_import_id;
        else
            UPDATE collection
            SET last_modified = NOW()
            WHERE import_id = NEW.collection_import_id;
        end if;
        RETURN NEW;
    END;
    $$ language 'plpgsql'""",
    )
    op.drop_entity(public_update_2_collection_last_modified)  # type: ignore

    public_update_2_family_last_modified = PGFunction(
        schema="public",
        signature="update_2_family_last_modified()",
        definition="""
    RETURNS TRIGGER AS $$
    BEGIN
        if tg_op = 'DELETE' then
            UPDATE family
            SET last_modified = NOW()
            WHERE import_id = OLD.family_import_id;
        else
            UPDATE family
            SET last_modified = NOW()
            WHERE import_id = NEW.family_import_id;
        end if;
        RETURN NEW;
    END;
    $$ language 'plpgsql'""",
    )
    op.drop_entity(public_update_2_family_last_modified)  # type: ignore

    public_update_1_last_modified = PGFunction(
        schema="public",
        signature="update_1_last_modified()",
        definition="""
    RETURNS TRIGGER AS $$
    BEGIN
        NEW.last_modified = NOW();
        RETURN NEW;
    END;
    $$ language 'plpgsql'""",
    )
    op.drop_entity(public_update_1_last_modified)  # type: ignore
    op.drop_index(op.f("ix_slug_family_import_id"), table_name="slug")
    op.drop_index(op.f("ix_slug_family_document_import_id"), table_name="slug")
    op.drop_index(op.f("ix_slug_collection_import_id"), table_name="slug")
    op.drop_table("slug")
    op.drop_index(op.f("ix_family_event_family_import_id"), table_name="family_event")
    op.drop_index(
        op.f("ix_family_event_family_document_import_id"), table_name="family_event"
    )
    op.drop_table("family_event")
    op.drop_index(op.f("ix_family_corpus_family_import_id"), table_name="family_corpus")
    op.drop_index(op.f("ix_family_corpus_corpus_import_id"), table_name="family_corpus")
    op.drop_table("family_corpus")
    op.drop_index(
        op.f("ix_physical_document_language_document_id"),
        table_name="physical_document_language",
    )
    op.drop_table("physical_document_language")
    op.drop_table("organisation_admin")
    op.drop_table("geo_statistics")
    op.drop_table("family_metadata")
    op.drop_index(
        op.f("ix_family_geography_family_import_id"), table_name="family_geography"
    )
    op.drop_table("family_geography")
    op.drop_index(
        op.f("ix_family_document_family_import_id"), table_name="family_document"
    )
    op.drop_table("family_document")
    op.drop_table("entity_counter")
    op.drop_index(op.f("ix_corpus_import_id"), table_name="corpus")
    op.drop_table("corpus")
    op.drop_table("collection_organisation")
    op.drop_index(
        op.f("ix_collection_family_family_import_id"), table_name="collection_family"
    )
    op.drop_table("collection_family")
    op.drop_table("variant")
    op.drop_table("physical_document")
    op.drop_table("organisation")
    op.drop_table("language")
    op.drop_index(op.f("ix_geography_slug"), table_name="geography")
    op.drop_table("geography")
    op.drop_index(op.f("ix_family_import_id"), table_name="family")
    op.drop_table("family")
    op.drop_table("corpus_type")
    op.drop_table("collection")
    op.drop_table("app_user")
    # ### end Alembic commands ###
