"""add corpus text and image

Revision ID: 0035
Revises: 0034
Create Date: 2024-04-30 11:22:43.893840

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0035"
down_revision = "0034"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("corpus", sa.Column("corpus_text", sa.Text(), nullable=True))
    op.add_column("corpus", sa.Column("corpus_image_url", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("corpus", "corpus_image_url")
    op.drop_column("corpus", "corpus_text")
    # ### end Alembic commands ###
