"""Remove FamilyEventType table

Revision ID: 0038
Revises: 0037
Create Date: 2024-06-27 11:18:04.834908

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0038"
down_revision = "0037"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("family_event_type")
    op.drop_constraint(
        "fk_family_event__event_type_name__family_event_type",
        "family_event",
        type_="foreignkey",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "fk_family_event__event_type_name__family_event_type",
        "family_event",
        "family_event_type",
        ["event_type_name"],
        ["name"],
    )
    op.create_table(
        "family_event_type",
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("name", name="pk_family_event_type"),
    )
    # ### end Alembic commands ###
