"""Update Entity Counter default counter value to 0.

Revision ID: 0039
Revises: 0038
Create Date: 2024-07-01 13:52:41.310560

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0039"
down_revision = "0038"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE entity_counter SET counter = 0 WHERE counter is NULL")
    op.alter_column(
        "entity_counter", "counter", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    op.execute("UPDATE entity_counter SET counter = NULL WHERE counter = 0")
    op.alter_column(
        "entity_counter", "counter", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###
