"""Use FK as prefix in counter

Revision ID: 0043
Revises: 0042
Create Date: 2024-07-08 13:11:33.721363

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0043"
down_revision = "0042"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("organisation", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.create_unique_constraint(op.f("uq_organisation__name"), "organisation", ["name"])
    op.drop_constraint("uq_entity_counter__prefix", "entity_counter", type_="unique")
    op.create_foreign_key(
        op.f("fk_entity_counter__prefix__organisation"),
        "entity_counter",
        "organisation",
        ["prefix"],
        ["name"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq_organisation__name"), "organisation", type_="unique")
    op.alter_column("organisation", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_constraint(
        op.f("fk_entity_counter__prefix__organisation"),
        "entity_counter",
        type_="foreignkey",
    )
    op.create_unique_constraint(
        "uq_entity_counter__prefix", "entity_counter", ["prefix"]
    )
    # ### end Alembic commands ###
