"""Use FK as prefix in counter

Revision ID: 0043
Revises: 0042
Create Date: 2024-07-08 12:09:05.575048

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0043"
down_revision = "0042"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_entity_counter__prefix", "entity_counter", type_="unique")
    op.create_foreign_key(
        op.f("fk_entity_counter__prefix__organisation"),
        "entity_counter",
        "organisation",
        ["prefix"],
        ["name"],
    )
    op.alter_column(
        "geography", "display_value", existing_type=sa.TEXT(), nullable=False
    )
    op.drop_constraint("ix_geography_slug", "geography", type_="unique")
    op.create_index(op.f("ix_geography_slug"), "geography", ["slug"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_geography_slug"), table_name="geography")
    op.create_unique_constraint("ix_geography_slug", "geography", ["slug"])
    op.alter_column(
        "geography", "display_value", existing_type=sa.TEXT(), nullable=True
    )
    op.drop_constraint(
        op.f("fk_entity_counter__prefix__organisation"),
        "entity_counter",
        type_="foreignkey",
    )
    op.create_unique_constraint(
        "uq_entity_counter__prefix", "entity_counter", ["prefix"]
    )
    # ### end Alembic commands ###
