"""Add organisation display name column

Revision ID: 0051
Revises: 0050
Create Date: 2024-07-30 11:05:27.032537

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0051"
down_revision = "0050"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organisation", sa.Column("display_name", sa.String(), nullable=True))
    op.execute(
        sa.text(
            "UPDATE organisation "
            "SET display_name = name "
            "WHERE display_name IS NULL"
        )
    )
    op.alter_column(
        "organisation", "display_name", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("organisation", "display_name")
    # ### end Alembic commands ###
