"""add geographies to family

Revision ID: 0053
Revises: 0052
Create Date: 2024-08-21 13:49:05.045639

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0053"
down_revision = "0052"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "family_geography",
        sa.Column("geography_id", sa.Integer(), nullable=False),
        sa.Column("family_import_id", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["family_import_id"],
            ["family.import_id"],
            name=op.f("fk_family_geography__family_import_id__family"),
        ),
        sa.ForeignKeyConstraint(
            ["geography_id"],
            ["geography.id"],
            name=op.f("fk_family_geography__geography_id__geography"),
        ),
        sa.PrimaryKeyConstraint(
            "geography_id", "family_import_id", name=op.f("pk_family_geography")
        ),
    )
    # ### end Alembic commands ###

    # Now copy the data from Family to FamilyGeography
    op.execute(
        """
        INSERT INTO family_geography (geography_id, family_import_id)
        SELECT geography_id, import_id
        FROM family
        WHERE geography_id IS NOT NULL
    """
    )


def downgrade():
    # No way back
    pass
