"""Allow geography_it to be unsed before removal

Revision ID: 0054
Revises: 0053
Create Date: 2024-08-27 13:12:23.720420

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0054"
down_revision = "0053"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("family", "geography_id", existing_type=sa.INTEGER(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "family", "geography_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
