"""Remove geography_id from Family

Revision ID: 0055
Revises: 0054
Create Date: 2024-09-26 15:48:47.550271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0055'
down_revision = '0054'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_family__geography_id__geography', 'family', type_='foreignkey')
    op.drop_column('family', 'geography_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family', sa.Column('geography_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_family__geography_id__geography', 'family', 'geography', ['geography_id'], ['id'])
    # ### end Alembic commands ###
