"""Add metadata field to FamilyEvent

Revision ID: 0056
Revises: 0055
Create Date: 2024-10-28 08:38:28.388759

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "0056"
down_revision = "0055"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "family_event",
        sa.Column(
            "valid_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("family_event", "valid_metadata")
    # ### end Alembic commands ###
