"""Add performance indexes for import_id columns

Revision ID: 0072
Revises: 0071
Create Date: 2025-09-23 10:00:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "0072"
down_revision = "0071"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Indexes for family_event table
    op.create_index(
        op.f("ix_family_event_family_import_id"),
        "family_event",
        ["family_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_family_event_family_document_import_id"),
        "family_event",
        ["family_document_import_id"],
        unique=False,
    )

    # Indexes for slug table
    op.create_index(
        op.f("ix_slug_family_import_id"),
        "slug",
        ["family_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slug_family_document_import_id"),
        "slug",
        ["family_document_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_slug_collection_import_id"),
        "slug",
        ["collection_import_id"],
        unique=False,
    )

    # Index for family_document table
    op.create_index(
        op.f("ix_family_document_family_import_id"),
        "family_document",
        ["family_import_id"],
        unique=False,
    )

    # Indexes for join tables
    op.create_index(
        op.f("ix_family_geography_family_import_id"),
        "family_geography",
        ["family_import_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_collection_family_family_import_id"),
        "collection_family",
        ["family_import_id"],
        unique=False,
    )
    # Note: ix_family_corpus_family_import_id already exists from migration 0067

    op.create_index(
        op.f("ix_physical_document_language_document_id"),
        "physical_document_language",
        ["document_id"],
        unique=False,
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop indexes in reverse order
    op.drop_index(op.f("ix_physical_document_language_document_id"), table_name="physical_document_language")
    op.drop_index(op.f("ix_collection_family_family_import_id"), table_name="collection_family")
    op.drop_index(op.f("ix_family_geography_family_import_id"), table_name="family_geography")
    op.drop_index(op.f("ix_family_document_family_import_id"), table_name="family_document")
    op.drop_index(op.f("ix_slug_collection_import_id"), table_name="slug")
    op.drop_index(op.f("ix_slug_family_document_import_id"), table_name="slug")
    op.drop_index(op.f("ix_slug_family_import_id"), table_name="slug")
    op.drop_index(op.f("ix_family_event_family_document_import_id"), table_name="family_event")
    op.drop_index(op.f("ix_family_event_family_import_id"), table_name="family_event")

    # ### end Alembic commands ###