repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-json
        exclude: tests/data/.*\.json

      - id: detect-aws-credentials
        args: [--allow-missing-credentials]

      - id: end-of-file-fixer
        exclude: ^.*\.egg-info/

  - repo: https://github.com/python-poetry/poetry
    rev: 1.7.1
    hooks:
      - id: poetry-check
        args: ["-C", "."]
# TODO more checks? e.g. bandit, safety, snyk, ...
